version: '3.6'

secrets:
  PORT:
    external: true

services:
  lunieapi:
    image: lunieapi:latest
    container_name: lunieapi
    restart: on-failure
    secrets:
    - PORT
    volumes:
    - /logs:/var/www/server/logs
    - ./pushCredentials.json:/var/www/server/pushCredentials.json
    networks:
       - general
    logging:
      driver: loki
      options:
        loki-url: "http://admin:${LOKI_PASSWORD}@monitoring.lunie.io:3100/loki/api/v1/push"
    deploy:
      replicas: 1
    environment:
      - HASURA_URL=$HASURA_URL
      - HASURA_ADMIN_KEY=$HASURA_ADMIN_KEY
      - SENTRY_DSN=$SENTRY_DSN
      - NODE_ENV=production
      - ENABLE_CACHE=true
      - REDIS_URL=http://redis:6379
      - PUBLIC_VAPID_KEY=BJwy1mP8njRNKyo2uPfjnB73tq6_HHXYnozMPaafCSBpdmoxe9RLYjC2DvRpDfUWoxY3c0-7R3ki9exKJ6cfe5k
      - PRIVATE_VAPID_KEY=$PRIVATE_VAPID_KEY
      - PUSH_NOTIFICATIONS_DATABASE_URL=https://lunie-push-notifications.firebaseio.com
      - PUSH_NOTIFICATIONS_FRONTEND_URL=https://app.lunie.io
      - EMONEY_EXCHANGE_API_RATES_ENDPOINT=https://api.exchangeratesapi.io/latest?
      - EMONEY_API_MAINNET=https://api.e-money.com/v1/
      - EMONEY_API_TESTNET=https://beta-api.e-money.com/v1/
  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /root/textfile_collector:/var/www
    - /:/rootfs:ro
    command:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --collector.textfile.directory=/var/www
    - --collector.filesystem.ignored-mount-points
    - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    restart: always
    networks:
       - general
    deploy:
      mode: global
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "lunieapi"
    restart: on-failure
    container_name: caddy
    networks:
       - general
    deploy:
      replicas: 1
    ports:
    - "80:80"
    - "443:443"
    - "9100:9100"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - ./caddy_certs:/root/.caddy
  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - general
    volumes:
      - ./redis_data:/data
volumes:
  caddy_certs:
  redis_data:
networks:
  general:

