version: 2.1

# Here we define all the paths and versions of images we want to play with
aliases:
  # Define paths and never think about them again
  - &WORKSPACE /tmp/voyager
  # Pick docker versions here only, then use the aliases in the executors definition
  - &docker-node circleci/node:10.15.3

# a reusable executor
executors:
  node:
    docker:
      - image: *docker-node
    working_directory: *WORKSPACE

jobs:
  build:
    docker:
      - image: node:10-alpine
    environment:
      TESTNET: 'true'
      TESTNET_RPC_URL: 'ws://localhost:26657/websocket'
      TESTNET_API_URL: 'http://localhost:9071'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

  # Create release.
  release:
    executor: node
    steps:
      - checkout
      - run: |
          yarn add simsala
          git config user.email "bot@lunie.io"
          git config user.name "Release Lunie Bot"
          node node_modules/simsala/src/cli.js release-candidate --semver patch --pending-path ./changes --owner luniehq --repository lunie --token $GIT_BOT_TOKEN --message "Please manually test before merging this to master"

workflows:
  releaseManually:
    jobs:
      - release:
          filters:
            branches:
              only: release
