version: 2.1
jobs:
  build:
    docker:
      - image: node:10-alpine
    environment:
      TESTNET: 'true'
      TESTNET_RPC_URL: 'ws://localhost:26657/websocket'
      TESTNET_API_URL: 'http://localhost:9071'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
