name: PR testing

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'api/**'
jobs:
  prep: 
    name: prep
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: go to subdirectory
      run: cd api
    - name: Install dependencies
      run: yarn install
  test:
    name: test
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - name: Test
        run: yarn test
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - name: Lint
        run: yarn lint 
  checkChangelog:
    name: checkChangelog
    runs-on: ubuntu-latest
    steps:
    - name: Add simsala
      run: npm install simsala
    - name: Check if changlog was updated
      run: node node_modules/simsala/src/cli.js check --pending-path ./changes
