name: App testing

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'app/**'
env:
  WORKING_DIRECTORY: ./app
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Test
        run: |
          yarn test:unit --coverage
          bash <(curl -s https://codecov.io/bash)
        working-directory: ${{env.WORKING_DIRECTORY}}
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Lint
        run: yarn lint 
        working-directory: ${{env.WORKING_DIRECTORY}}
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Run E2E tests
        run: yarn test:e2e:browserstack --fe=https://deploy-preview-${{github.event.client_payload.pull_request.number}}--lunieio.netlify.app --api=https://production-api.lunie.io
        working-directory: ${{env.WORKING_DIRECTORY}}
        env:
          PASSWORD: ${{secrets.GAIA_PASSWORD}}
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
  checkChangelog:
    name: checkChangelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Check if changlog was updated
        run: npx simsala check --pending-path ./changes
        working-directory: ${{env.WORKING_DIRECTORY}}
