name: Publish on Netlify
on:
  push:
    branches:
      - "master"
    paths:
      - 'app/CHANGELOG.md'

env:
  WORKING_DIRECTORY: ./app
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Build
        run: yarn buildsentry
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN_APP }}
        working-directory: ${{env.WORKING_DIRECTORY}}
      - uses: nwtgck/actions-netlify@v1.1.1
        id: deploy
        with:
          production-branch: master
          publish-dir: './app/dist'
          github-token: ${{ secrets.GIT_BOT_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          netlify-config-path: ./app/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}