name: App PR testing

on:
  pull_request:
    branches:
      - "*"
    paths:
      - 'app/**'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: app
      - name: go to subdirectory
        run: cd app
      - name: Test
        run: |
          yarn test:unit --coverage
          bash <(curl -s https://codecov.io/bash)
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: app
      - name: go to subdirectory
        run: cd app
      - name: Lint
        run: yarn lint 
  checkChangelog:
    name: checkChangelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Add simsala
        run: npm install simsala
      - name: Check if changlog was updated
        run: node node_modules/simsala/src/cli.js check --pending-path ./changes
