name: Publish on Netlify
on:
  pull_request:
    branches-ignore:
      - "master"
    paths:
      - 'app/**'

env:
  WORKING_DIRECTORY: ./app
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Build
        run: yarn build
        working-directory: ${{env.WORKING_DIRECTORY}}
      - run: ls -la app/dist
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --branch=${{ github.head_ref }}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  e2e:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Run E2E tests
        run: yarn test:e2e:browserstack --fe=https://$(echo "${{github.head_ref}}" | sed "s/\//-/")--lunieio.netlify.app --api=https://production-api.lunie.io
        working-directory: ${{env.WORKING_DIRECTORY}}
        env:
          PASSWORD: ${{secrets.GAIA_PASSWORD}}
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}