name: Extension publishing

on:
  pull_request:
    branches:
      - "master"
    paths:
      - 'extension/CHANGELOG.md'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Init submodule # DEPRECATE
        run: npm run initiate-submodule
      - uses: bahmutov/npm-install@v1 # DEPRECATE
        with:
          working-directory: ${{env.WORKING_DIRECTORY}}/lunie
      - name: Build
        run: LUNIE_API=${{ secrets.LUNIE_API }} yarn build
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Zip
        run: yarn build-zip
        working-directory: ${{env.WORKING_DIRECTORY}}
      - name: Deploy
        run: sh ./scripts/deploy.sh ./dist-zip/lunie-browser-extension.zip
        working-directory: ${{env.WORKING_DIRECTORY}}
